//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTap
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        public string MaDon { get; set; }
        public string TenPhim { get; set; }
        public string QuocGia { get; set; }
        public string TheLoai { get; set; }
        public Nullable<System.DateTime> NgayCongChieu { get; set; }
        public Nullable<int> DoTuoiQuyDinh { get; set; }
        public Nullable<decimal> GiaTienPhuThu { get; set; }
        public string DinhDang { get; set; }
        public string TenPhuThu { get; set; }
    }
}
